services:
 
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
      - back-end
    networks:
      - softy-pinko-network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile  

networks:
  softy-pinko-network:
    driver: bridge
