# Use the last picture Ubuntu like a basic
FROM ubuntu:latest
# Update APT and upgrade existing packages
RUN apt-get update && apt-get upgrade -y
# Commande to execute on container/
CMD echo "Hello, World!"
